### ISSUE TITLE
HISTORY file

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#11]
It is common to make a dedicated `HISTORY.md` file to contain the history that is at the bottom of the README. Just a suggestion!

**Comment by gmorello** [comment]
Done, thanks

**Comment by gmorello** [comment]
Maybe also this issue can be closed.
I will have to update to v1.0.2 after finishing the revision.

**Comment by steven-murray** [comment]
Yup, this looks good to me!
