### ISSUE TITLE
Community Guidelines

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#12]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

It is currently hard to know how to contribute to the repository. There are no explicit instructions, and the workings of the package are rather opaque (also due to #9). 

It would be highly beneficial to create a simple `CONTRIBUTING.md` file, which outlines how to contribute to the software, how to make issues, etc.

**Comment by gmorello** [comment]
I created a basic CONTRIBUTING.md file. Is that ok?

**Comment by steven-murray** [comment]
It is very basic, and I encourage further additions to it, but it exists!

**Comment by gmorello** [comment]
Ok, thanks. If you would like to point at some examples with other ways of contributing that I can consider, but at least this issue is not critical for releasing the first static version outside GitHub.

**Comment by steven-murray** [comment]
Here's an example of what I consider to be a fairly complete contributing guide, that you'd probably have to prune a bit: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/.github/CONTRIBUTING.md
