### ISSUE TITLE
Code Description

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#13]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

The current description of the project is this:

    This repository stores codes to help modeling exoplanetary transits and eclipsing binaries.

This could be both more explicit and more appealing, perhaps something like

    ExoTETHyS is an open-source package for modeling expolanetary transits and eclipsing binaries.    It provides pure-pythonic interfaces to the popular(?) `sail` and `trip` algorithms, along with a host of new improvements.

**Comment by gmorello** [comment]
What about
`ExoTETHyS is an open-source package for modeling exoplanetary transits, eclipsing binaries and related phenomena.`

For example, just computing the limb-darkening coefficients is not "modeling a transit", but it is something needed to do that.

**Comment by steven-murray** [comment]
That sounds great.

**Comment by gmorello** [comment]
Done, thanks.
