### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by williamjameshandley** [ucl-exoplanets/ExoTETHyS#14]
This project should have a rudimentary continuous integration set up which can be extended as time goes on.

In my experience, the simplest form of python CI is [Travis](https://docs.travis-ci.com/) combined with `pytest`. There are plenty of resources online, and I can point you to a few as necessary, but [this hello world example](https://github.com/kevchn/travis-ci-pytest) has served me pretty well in the past.

For now, a working travis setup which runs the two examples in the README would would suffice to resolve this issue. That setup would serve to (a) test the installation and (b) check that it runs without error.

Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834)

**Comment by steven-murray** [comment]
Looks like this is being addressed in #10

**Comment by gmorello** [comment]
Yes, I actually followed the instructions from the example linked here before answering in #10.
Given the redundancy I close this issue so that we continue the discussion in #10.
