### ISSUE TITLE
Make repository pip-installable

### ISSUE THREAD

**Issue by williamjameshandley** [ucl-exoplanets/ExoTETHyS#15]
It would be good to twine upload this repository to [PyPi](https://pypi.org/) so that it is pip installable without having to clone the repository.

The tutorial on [python.org](https://packaging.python.org/tutorials/packaging-projects/) has served me well in the past for getting this up and running.

Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834)

**Comment by gmorello** [comment]
I answered all the other issues. If they can be closed, I will consider this version as stable in order to upload to PyPi (and Zenodo, as recommended by the AAS reviewers).

**Comment by gmorello** [comment]
Added on Pypi, thanks.
One question: now that it is done, if I want to update just the README or the examples, do I have to:
1) repeat the whole upload procedure;
2) changing the version number?

**Comment by williamjameshandley** [comment]
Best practice is to re-upload to PyPi whenever you decide to update [the version number](https://semver.org/), which is typically at a slower rate than things like README updates or other small software alterations.

**Comment by gmorello** [comment]
Ok, thanks for the directions
