### ISSUE TITLE
bad module name

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#16]
This  is a very strange module name, and also a star import:

https://github.com/ucl-exoplanets/ExoTETHyS/blob/1350a9f7cbbe91fd41b306c057b49cd3e1131300/exotethys/sail.py#L21

I recommend renaming the module to `_database.py`, and then doing `from ._database import Database` (and whatever other parts of the module you require) explicitly.

**Comment by gmorello** [comment]
Done
