### ISSUE TITLE
Depreciation warnings recent numpy and scipy versions.

### ISSUE THREAD

**Issue by jeroenbouwman** [ucl-exoplanets/ExoTETHyS#24]
Hi, I get the following depreciation warning with the more resent version of numpy:

sail.py:1293: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
log_waves = np.linspace(log_lambda1, log_lambda2, num=np.int(n_steps))

So I guess this is a trivial change of np.int() to int()

I also get a depreciation warning on one of the scipy functions:
optimize.py:646: DeprecationWarning: xtol is deprecated for Nelder-Mead, use xatol instead. If you specified both, only xatol is used. 

But this warning did not state a line in the exotethys package so I', not sure this last warning is an issue for this package.

**Comment by gmorello** [comment]
Hi Jeroen, both warnings should be fixed now. Thank you
