### ISSUE TITLE
upload new version of Exotethys to pypi

### ISSUE THREAD

**Issue by jeroenbouwman** [ucl-exoplanets/ExoTETHyS#27]
Given the substantial differences between the current master branch of Exotethys on Github and the version 2.0 currently on PyPi, it would be good if a new version of Exotethys could be uploaded to Pypi. This would also help the creation of other PyPi packages which depend on Exotethys as a direct link to the github repository is not possible when creating pypi packages.

**Comment by gmorello** [comment]
Hi Jeroen, I uploaded the current version to Pypi. Let me know if it works, thanks.
