### ISSUE TITLE
Header of README is garbled

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#3]
As part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834)

The header of the README seems to not be rendering correctly, especially the [//] notation.

**Comment by gmorello** [comment]
Corrected, thanks

**Comment by steven-murray** [comment]
The lines

```
[//]: # (## Dependencies)

[//]: # (The code is consistent with python2/3. It makes use of)
[//]: # (- numpy, scipy, os, sys, glob, time, shutil, copy, pickle, astropy.io.fits, matplotlib)
```

are still missing from the rendering... is this intentional?

**Comment by gmorello** [comment]
Yes, it is. I was thinking about providing minimum versions as you state in #5. What about the solution that I propose in #5?

**Comment by gmorello** [comment]
Finally, dependencies added.
This issue should be closed as well.
