### ISSUE TITLE
update to sail.py

### ISSUE THREAD

**Issue by jeroenbouwman** [ucl-exoplanets/ExoTETHyS#33]
in the sail.py module (perhaps also in other modules) the following import is made:

from scipy.integrate import simps

for newer scipy version the name has changed to simpson. Could you edit the code such that the import reads:

from scipy.integrate import simpson

**Comment by gmorello** [comment]
Hi Jeroen,
This should have been already solved in #32.
Try pip installing the new version, and let me know if it does not work.
Many thanks

**Comment by jeroenbouwman** [comment]
I updated to the 2.0.12 version from pypi. I now get the following error:

File "exotethys/sail.py", line 2005, in get_passband_intensities
    my_ints_integ = simpson(my_ints*my_pce[:,None]*my_waves.value[:,None], my_waves.value, axis=0)
TypeError: simpson() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by gmorello** [comment]
Yes, I just noted that this problem occurs with scipy version 1.14.0. ExoTETHyS 2.0.13 should work with all scipy versions.
Thanks.
