### ISSUE TITLE
depreciation of pkg_resources

### ISSUE THREAD

**Issue by jeroenbouwman** [ucl-exoplanets/ExoTETHyS#34]
there is a depreciation warning for the  pkg_resources module imported and used in the sail module:

exotethys/sail.py:14: DeprecationWarning:pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

for the a next version of exotethys one should switch to importlib.resources and importlib.metadata

**Comment by gmorello** [comment]
Done, thanks
