### ISSUE TITLE
Build fails for Python 3.12

### ISSUE THREAD

**Issue by atsiaras** [ucl-exoplanets/ExoTETHyS#35]
Hi there! 

It seems that in Python 3.12 the ```pkg_resources``` package is not supported:

``` python
import pkg_resources
E   ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by gmorello** [comment]
Hi Angelos, thank you! It should be solved, checked for the new ExoTETHyS version (2.0.14) in < 1 hour
