### ISSUE TITLE
dynamic MANIFEST

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#4]
As part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

Creating a MANIFEST dynamically in a `setup.py` like in the following line:
https://github.com/ucl-exoplanets/ExoTETHyS/blob/6a3909a52dcea93ded6805d6220cc5247db4cae8/setup.py#L13
is to my knowledge highly uncommon practice. There are ways to dynamically include stuff in the MANIFEST file within the file specification itself. 

Is there a good reason to do this?

**Comment by steven-murray** [comment]
Sorry for the late reply! Here's a pretty detailed list of suggestions for MANIFEST.in: https://www.reddit.com/r/Python/comments/40s8qw/simplify_your_manifestin_commands/

**Comment by gmorello** [comment]
I modified the setup.py without creating the MANIFEST.in as it is unnecessary.
Is that fine for you?

**Comment by steven-murray** [comment]
absolutely.
