### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#5]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

The requirements as specified have no version specifications. It is typically helpful to have at least some minimum version specified:

https://github.com/ucl-exoplanets/ExoTETHyS/blob/6a3909a52dcea93ded6805d6220cc5247db4cae8/setup.py#L9

**Comment by gmorello** [comment]
The code was originally written to work with quite old python2 libraries, but it may be quite annoying to dowgrade the libraries to see the minimum versions for the code to work. Could I just state the (new) versions for which it is guaranteed in the documentation, but without setting stringent requirements?

**Comment by steven-murray** [comment]
I don't think you have to find the absolute minimum required versions for the packages -- you can probably set them reasonably to whatever you have installed in your current environment. They can always be downgraded over time as well.

**Comment by gmorello** [comment]
Done

**Comment by steven-murray** [comment]
This does not seem to be done to me: the `install_requires` keyword has been taken out of `setup.py`. This will break automatic installation using `pip`. You _can_ read the `requirements.txt` into your setup.py if you wish to reduce redundancy.

**Comment by gmorello** [comment]
I have just re-added the install_requires
