### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#6]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

As far as I know, it is generally discouraged to install python packages with `python setup.py install` as this will not keep track of all installed files and so is not easily uninstallable. It is better to recommend installation using `pip install .`. 

I will note that doing the following did *not* work for me:
```
conda create -n exotethys python=3
pip install . # from top-level directory of ExoTETHyS
```
but that might just be my own problem. Conda-installing `maptlotlib scipy astropy` then trying `pip install .` seems to have worked fine.

You may want to mention (depending on your intended audience) that creating a fresh environment (`venv` or `conda`) is encouraged.

**Comment by gmorello** [comment]
It works with `pip install .`
I do not often use environments, but I will consider it.
So maybe this issue can also be closed.

**Comment by steven-murray** [comment]
The README does now say to use `pip install .`, so I consider this good enough.
