### ISSUE TITLE
Irregular imports

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#8]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834):

This is a highly irregular/discouraged way to do imports:

https://github.com/ucl-exoplanets/ExoTETHyS/blob/ec6c6e8fb9d4fcc8f22c07556db2ce30c157c44b/exotethys/_1databases.py#L6

I recommend importing modules directly into your module.

**Comment by gmorello** [comment]
Replaced with "import package" for all packages that were imported through ._0imports

**Comment by gmorello** [comment]
I checked all the import, reinstalled the code and it still works.
I think this issue can be closed.

**Comment by steven-murray** [comment]
I think then that `_0imports.py` can be removed.

**Comment by gmorello** [comment]
Done, thanks
