### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by steven-murray** [ucl-exoplanets/ExoTETHyS#9]
Part of JOSS [review](https://github.com/openjournals/joss-reviews/issues/1834)

It seems that none of the functions in ExoTETHyS have docstrings, which makes it hard to know how to use it, beyond the examples in the README. Some of the functions do have comments which approximate a docstring, and at the very least, these should be converted to docstrings.

**Comment by gmorello** [comment]
Docstrings completed for sail.py.
I will soon start writing the docstrings for trip.py.

**Comment by steven-murray** [comment]
Those docstrings look good!

**Comment by gmorello** [comment]
Docstrings are now completed also for trip.py.
Can this issue be closed?

**Comment by steven-murray** [comment]
Yup, great!
